apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-nodejs-gitops
  labels:
    app.kubernetes.io/part-of: hello
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: hello-nodejs-gitops
spec:
  template:
    metadata:
      annotations:
        conventions.apps.tanzu.vmware.com/applied-conventions: appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: hello
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: hello-nodejs-gitops
    spec:
      containers:
      - image: ghcr.io/dbha/tap/supply-chain/hello-nodejs-gitops-demo@sha256:aa3e58d0e7a111f599d05080a5186839105e983b5c28c3f0fb818cb4697df25c
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

